version: '3'

services:
  client:
    build: ./client
    ports:
      - 3000:3000
    env_file:
      - ./client/.env
    volumes:
      - ./client:/code/client

  microservice:
    build: ./microservice
    env_file:
      - ./microservice/.env
    depends_on:
      - postgres
    volumes:
      - ./microservice:/code/microservice

  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=huma_user
      - POSTGRES_PASSWORD=huma_pass
      - POSTGRES_DB=huma_db
      # - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  client:
  microservice:
  pgdata: