version: '3'

services:
  client:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/code/client

  microservice:
    build: ./microservice
    ports:
      - 3001:3001
    env_file:
      - ./microservice/.env
    volumes:
      - ./microservice:/code/microservice

  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=huma_user
      - POSTGRES_PASSWORD=huma_pass
      - POSTGRES_DB=huma_db  
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  
volumes:
  client:
  microservice:
  pgdata: